// Autogenerated from Pigeon (v2.0.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class HelpCrunchInitializationParams;
@class HelpCrunchUser;

@interface HelpCrunchInitializationParams : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithHelpCrunchAppId:(NSNumber *)helpCrunchAppId
    organizationName:(NSString *)organizationName
    appSecret:(NSString *)appSecret;
@property(nonatomic, strong) NSNumber * helpCrunchAppId;
@property(nonatomic, copy) NSString * organizationName;
@property(nonatomic, copy) NSString * appSecret;
@end

@interface HelpCrunchUser : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithId:(NSString *)id
    name:(nullable NSString *)name
    email:(nullable NSString *)email
    company:(nullable NSString *)company
    phone:(nullable NSString *)phone
    customData:(nullable NSDictionary<NSString *, id> *)customData;
@property(nonatomic, copy) NSString * id;
@property(nonatomic, copy, nullable) NSString * name;
@property(nonatomic, copy, nullable) NSString * email;
@property(nonatomic, copy, nullable) NSString * company;
@property(nonatomic, copy, nullable) NSString * phone;
@property(nonatomic, strong, nullable) NSDictionary<NSString *, id> * customData;
@end

/// The codec used by HelpCrunchPlugin.
NSObject<FlutterMessageCodec> *HelpCrunchPluginGetCodec(void);

@protocol HelpCrunchPlugin
- (void)initializeParams:(HelpCrunchInitializationParams *)params completion:(void(^)(FlutterError *_Nullable))completion;
- (void)showChatScreenWithCompletion:(void(^)(FlutterError *_Nullable))completion;
- (void)updateUserUser:(HelpCrunchUser *)user completion:(void(^)(FlutterError *_Nullable))completion;
- (void)logoutUserWithCompletion:(void(^)(FlutterError *_Nullable))completion;
@end

extern void HelpCrunchPluginSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<HelpCrunchPlugin> *_Nullable api);

NS_ASSUME_NONNULL_END
